# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1526d267b747a8f69c5e650ac91fa604774ffcde2897972b76cdacb508e4f3969b74b0c897823ce8186623f2ead1b03c28cb00053e1cb141bd8996a0c53e17e4

test:
  secret_key_base: 154978fc8235a4136335fbdd7506a0708d8fc07062f99320d86c72d64d3713c7da6b564735af5afa6569efca740229e0401833a73f6928b28e33750bbe3ed815

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
